name: psi4demo
channels:
    - psi4
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - psi4=1.6.1
    - numpy>=1.22.3,<1.23.0
    - matplotlib
    - jupyterlab
    - pip:
        - pythreejs
        - fortecubeview
